### ISSUE TITLE
Run multiple tasks in one command

### ISSUE THREAD

**Issue by Michael-Kruggel** [defenseunicorns/maru-runner#80] opened 2023-11-28 18:06 UTC
### Is your feature request related to a problem? Please describe

I would like to be able to run multiple tasks in one command, e.g. `uds run task1 task2 task3`. The state of the program for each task should be independent, e.g. a variable set in `task1` should not be persistent when running `task2`

### Describe the solution you'd like

- **Given** I enter multiple valid tasks into `uds run`
- **When** I enter the command
- **Then** it runs the task in the order it is listed

**Comment by oates** [comment] 2024-06-07 14:43
Is this still something you need @Michael-Kruggel . We are doing some grooming this morning. If so, can you give more context?

What is the main use case for this?

**Comment by JoeHCQ1** [comment] 2024-09-10 15:41
I'd give a use case @oates which is reduce total time to wait for a set of tasks to complete. i.e. parallelization.

**Comment by Michael-Kruggel** [comment] 2024-09-10 16:59
I agree with what @JoeHCQ1 said. I don't remember the reason for the original request, but can still see this as a valuable add. More of a nice to have than a need to have

**Comment by Racer159** [comment] 2024-10-22 22:18
Closing as a dupe of 138

**Closed by Racer159** 2024-10-22 22:18 UTC
Labels: good first issue
